version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mynetwork

  nodeapp:
    image: emmrylmz/hubx-node-demo
    build: .
    volumes:
      - .:/app              
      - /app/node_modules 
    environment:
      MONGO_URI: ${MONGO_URI}
      DB_NAME: ${DB_NAME}
      NODE_ENV: ${NODE_ENV}
    networks:
      - mynetwork
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    command: npm start

networks:
  mynetwork:
    driver: bridge

volumes:
  mongo_data:
